name: Deploy CityLab Security

# Aciona o workflow apenas quando houver push na branch main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Isso diz para rodar no Raspberry Pi, não na nuvem do GitHub
    
    steps:
    # Baixa a versão mais recente do código
    - name: Check out repository
      uses: actions/checkout@v4
      
    # Atualiza dependências 
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # Reinicia o serviço do projeto
    - name: Restart Application
      run: |
        echo "Reiniciando serviço de segurança..."
        sudo systemctl restart citylab.service