name: Deploy CityLab Security

# Aciona o workflow apenas quando houver push na branch main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Isso diz para rodar no Raspberry Pi, n√£o na nuvem do GitHub
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        VENV_PATH="/home/citylab/Desktop/Projects/CityLab_Security/citylab_venv"
        $VENV_PATH/bin/python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then $VENV_PATH/bin/pip install -r requirements.txt; fi
    
    - name: Restart Application
      run: |
        sudo systemctl restart citylab.service